[2024-11-27T01:47:17.568+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T01:47:17.576+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data manual__2024-11-27T01:47:16.122432+00:00 [queued]>
[2024-11-27T01:47:17.580+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data manual__2024-11-27T01:47:16.122432+00:00 [queued]>
[2024-11-27T01:47:17.580+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-27T01:47:17.586+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_citibike_data> on 2024-11-27 01:47:16.122432+00:00
[2024-11-27T01:47:17.592+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29349) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T01:47:17.591+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Citibike_Hist_Data_ETL', 'extract_citibike_data', 'manual__2024-11-27T01:47:16.122432+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/ETL_citibike.py', '--cfg-path', '/tmp/tmpjpax60ql']
[2024-11-27T01:47:17.593+0000] {standard_task_runner.py:63} INFO - Started process 29352 to run task
[2024-11-27T01:47:17.594+0000] {standard_task_runner.py:91} INFO - Job 293: Subtask extract_citibike_data
[2024-11-27T01:47:17.635+0000] {task_command.py:426} INFO - Running <TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data manual__2024-11-27T01:47:16.122432+00:00 [running]> on host 5de3b6ca18a7
[2024-11-27T01:47:17.695+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Citibike_Hist_Data_ETL' AIRFLOW_CTX_TASK_ID='extract_citibike_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T01:47:16.122432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T01:47:16.122432+00:00'
[2024-11-27T01:47:17.696+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T01:47:17.697+0000] {logging_mixin.py:188} INFO - Fetching citibike ride data from 2021-10 to 2024-10
[2024-11-27T01:47:17.707+0000] {logging_mixin.py:188} INFO - Failed to process JC-202110-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202110-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff83a9e4b0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.717+0000] {logging_mixin.py:188} INFO - Failed to process JC-202111-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202111-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f7c80>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.723+0000] {logging_mixin.py:188} INFO - Failed to process JC-202112-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202112-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6578c620>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.726+0000] {logging_mixin.py:188} INFO - Failed to process JC-202201-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202201-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f6c60>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.728+0000] {logging_mixin.py:188} INFO - Failed to process JC-202202-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202202-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65634a70>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.731+0000] {logging_mixin.py:188} INFO - Failed to process JC-202203-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202203-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65635310>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.734+0000] {logging_mixin.py:188} INFO - Failed to process JC-202204-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202204-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65635c70>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.736+0000] {logging_mixin.py:188} INFO - Failed to process JC-202205-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202205-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65636690>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.739+0000] {logging_mixin.py:188} INFO - Failed to process JC-202206-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202206-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65637110>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.742+0000] {logging_mixin.py:188} INFO - Failed to process JC-202207-citbike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202207-citbike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff83a9dbe0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.745+0000] {logging_mixin.py:188} INFO - Failed to process JC-202208-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202208-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65636150>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.748+0000] {logging_mixin.py:188} INFO - Failed to process JC-202209-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202209-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65635340>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.751+0000] {logging_mixin.py:188} INFO - Failed to process JC-202210-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202210-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65634200>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.754+0000] {logging_mixin.py:188} INFO - Failed to process JC-202211-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202211-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656377a0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.758+0000] {logging_mixin.py:188} INFO - Failed to process JC-202212-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202212-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563c080>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.762+0000] {logging_mixin.py:188} INFO - Failed to process JC-202301-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202301-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656349e0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.766+0000] {logging_mixin.py:188} INFO - Failed to process JC-202302-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202302-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65635370>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.769+0000] {logging_mixin.py:188} INFO - Failed to process JC-202303-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202303-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656366c0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.771+0000] {logging_mixin.py:188} INFO - Failed to process JC-202304-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202304-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f7830>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.775+0000] {logging_mixin.py:188} INFO - Failed to process JC-202305-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202305-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563c890>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.778+0000] {logging_mixin.py:188} INFO - Failed to process JC-202306-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202306-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563d250>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.782+0000] {logging_mixin.py:188} INFO - Failed to process JC-202307-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202307-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65634d40>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.785+0000] {logging_mixin.py:188} INFO - Failed to process JC-202308-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202308-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656352b0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.787+0000] {logging_mixin.py:188} INFO - Failed to process JC-202309-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202309-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65634d10>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.791+0000] {logging_mixin.py:188} INFO - Failed to process JC-202310-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202310-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563c6e0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.793+0000] {logging_mixin.py:188} INFO - Failed to process JC-202311-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202311-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563d8b0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.797+0000] {logging_mixin.py:188} INFO - Failed to process JC-202312-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202312-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563e120>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.800+0000] {logging_mixin.py:188} INFO - Failed to process JC-202401-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202401-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65635cd0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.803+0000] {logging_mixin.py:188} INFO - Failed to process JC-202402-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202402-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65636870>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.806+0000] {logging_mixin.py:188} INFO - Failed to process JC-202403-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202403-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f77a0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.811+0000] {logging_mixin.py:188} INFO - Failed to process JC-202404-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202404-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563c590>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.814+0000] {logging_mixin.py:188} INFO - Failed to process JC-202405-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202405-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563e6c0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.820+0000] {logging_mixin.py:188} INFO - Failed to process JC-202406-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202406-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563ef30>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.825+0000] {logging_mixin.py:188} INFO - Failed to process JC-202407-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202407-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65634230>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.827+0000] {logging_mixin.py:188} INFO - Failed to process JC-202408-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202408-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65634200>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.830+0000] {logging_mixin.py:188} INFO - Failed to process JC-202409-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202409-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65637bf0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.835+0000] {logging_mixin.py:188} INFO - Failed to process JC-202410-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202410-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65636b10>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T01:47:17.835+0000] {logging_mixin.py:188} INFO - No data extracted for given range.
[2024-11-27T01:47:17.835+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-27T01:47:17.836+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T01:47:17.841+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Citibike_Hist_Data_ETL, task_id=extract_citibike_data, run_id=manual__2024-11-27T01:47:16.122432+00:00, execution_date=20241127T014716, start_date=20241127T014717, end_date=20241127T014717
[2024-11-27T01:47:17.858+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-27T01:47:17.873+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-27T01:47:17.874+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
