[2024-11-26T22:07:43.702+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T22:07:43.709+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data scheduled__2024-11-25T21:30:00+00:00 [queued]>
[2024-11-26T22:07:43.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data scheduled__2024-11-25T21:30:00+00:00 [queued]>
[2024-11-26T22:07:43.713+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-26T22:07:43.719+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_citibike_data> on 2024-11-25 21:30:00+00:00
[2024-11-26T22:07:43.726+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=22752) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T22:07:43.728+0000] {standard_task_runner.py:63} INFO - Started process 22771 to run task
[2024-11-26T22:07:43.727+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Citibike_Hist_Data_ETL', 'extract_citibike_data', 'scheduled__2024-11-25T21:30:00+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/ETL_citibike.py', '--cfg-path', '/tmp/tmp7308lwjb']
[2024-11-26T22:07:43.728+0000] {standard_task_runner.py:91} INFO - Job 264: Subtask extract_citibike_data
[2024-11-26T22:07:43.758+0000] {task_command.py:426} INFO - Running <TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data scheduled__2024-11-25T21:30:00+00:00 [running]> on host 5de3b6ca18a7
[2024-11-26T22:07:43.801+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Citibike_Hist_Data_ETL' AIRFLOW_CTX_TASK_ID='extract_citibike_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T21:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T21:30:00+00:00'
[2024-11-26T22:07:43.801+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T22:07:43.803+0000] {logging_mixin.py:188} INFO - Fetching citibike ride data from 2021-10 to 2024-10
[2024-11-26T22:07:43.809+0000] {logging_mixin.py:188} INFO - Failed to process JC-202110-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202110-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff66d6bb30>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.819+0000] {logging_mixin.py:188} INFO - Failed to process JC-202111-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202111-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f7dd0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.827+0000] {logging_mixin.py:188} INFO - Failed to process JC-202112-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202112-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65590e00>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.831+0000] {logging_mixin.py:188} INFO - Failed to process JC-202201-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202201-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f7440>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.834+0000] {logging_mixin.py:188} INFO - Failed to process JC-202202-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202202-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f72f0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.837+0000] {logging_mixin.py:188} INFO - Failed to process JC-202203-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202203-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639460>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.840+0000] {logging_mixin.py:188} INFO - Failed to process JC-202204-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202204-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639e80>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.844+0000] {logging_mixin.py:188} INFO - Failed to process JC-202205-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202205-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563a8a0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.848+0000] {logging_mixin.py:188} INFO - Failed to process JC-202206-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202206-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563b320>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.851+0000] {logging_mixin.py:188} INFO - Failed to process JC-202207-citbike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202207-citbike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f72f0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.854+0000] {logging_mixin.py:188} INFO - Failed to process JC-202208-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202208-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563a420>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.857+0000] {logging_mixin.py:188} INFO - Failed to process JC-202209-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202209-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656393d0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.861+0000] {logging_mixin.py:188} INFO - Failed to process JC-202210-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202210-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656384d0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.863+0000] {logging_mixin.py:188} INFO - Failed to process JC-202211-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202211-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563bad0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.867+0000] {logging_mixin.py:188} INFO - Failed to process JC-202212-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202212-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563c560>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.871+0000] {logging_mixin.py:188} INFO - Failed to process JC-202301-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202301-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656388c0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.874+0000] {logging_mixin.py:188} INFO - Failed to process JC-202302-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202302-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639ac0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.877+0000] {logging_mixin.py:188} INFO - Failed to process JC-202303-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202303-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6582b4d0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.881+0000] {logging_mixin.py:188} INFO - Failed to process JC-202304-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202304-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563c710>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.887+0000] {logging_mixin.py:188} INFO - Failed to process JC-202305-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202305-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563d100>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.891+0000] {logging_mixin.py:188} INFO - Failed to process JC-202306-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202306-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563db80>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.895+0000] {logging_mixin.py:188} INFO - Failed to process JC-202307-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202307-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563a330>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.899+0000] {logging_mixin.py:188} INFO - Failed to process JC-202308-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202308-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639850>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.904+0000] {logging_mixin.py:188} INFO - Failed to process JC-202309-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202309-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563b3b0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.907+0000] {logging_mixin.py:188} INFO - Failed to process JC-202310-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202310-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563cdd0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.911+0000] {logging_mixin.py:188} INFO - Failed to process JC-202311-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202311-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563e240>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.916+0000] {logging_mixin.py:188} INFO - Failed to process JC-202312-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202312-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563ebd0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.922+0000] {logging_mixin.py:188} INFO - Failed to process JC-202401-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202401-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65638a10>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.925+0000] {logging_mixin.py:188} INFO - Failed to process JC-202402-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202402-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656398b0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.929+0000] {logging_mixin.py:188} INFO - Failed to process JC-202403-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202403-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563e390>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.932+0000] {logging_mixin.py:188} INFO - Failed to process JC-202404-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202404-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563d160>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.937+0000] {logging_mixin.py:188} INFO - Failed to process JC-202405-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202405-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563f1d0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.940+0000] {logging_mixin.py:188} INFO - Failed to process JC-202406-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202406-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563f2f0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.945+0000] {logging_mixin.py:188} INFO - Failed to process JC-202407-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202407-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656395e0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.949+0000] {logging_mixin.py:188} INFO - Failed to process JC-202408-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202408-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65638890>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.953+0000] {logging_mixin.py:188} INFO - Failed to process JC-202409-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202409-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563be60>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.960+0000] {logging_mixin.py:188} INFO - Failed to process JC-202410-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202410-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563f1d0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-26T22:07:43.961+0000] {logging_mixin.py:188} INFO - No data extracted for given range.
[2024-11-26T22:07:43.961+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-26T22:07:43.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T22:07:43.966+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Citibike_Hist_Data_ETL, task_id=extract_citibike_data, run_id=scheduled__2024-11-25T21:30:00+00:00, execution_date=20241125T213000, start_date=20241126T220743, end_date=20241126T220743
[2024-11-26T22:07:43.988+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-26T22:07:43.999+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-26T22:07:44.000+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
