[2024-11-26T09:20:32.485+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T09:20:32.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Hist_Data_ETL.load_weather_hist_data manual__2024-11-26T09:20:29.197633+00:00 [queued]>
[2024-11-26T09:20:32.496+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Hist_Data_ETL.load_weather_hist_data manual__2024-11-26T09:20:29.197633+00:00 [queued]>
[2024-11-26T09:20:32.496+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-26T09:20:32.501+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_hist_data> on 2024-11-26 09:20:29.197633+00:00
[2024-11-26T09:20:32.505+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2991) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T09:20:32.506+0000] {standard_task_runner.py:63} INFO - Started process 2994 to run task
[2024-11-26T09:20:32.505+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Hist_Data_ETL', 'load_weather_hist_data', 'manual__2024-11-26T09:20:29.197633+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/ETL_weather_historical.py', '--cfg-path', '/tmp/tmp0d7d55c1']
[2024-11-26T09:20:32.507+0000] {standard_task_runner.py:91} INFO - Job 165: Subtask load_weather_hist_data
[2024-11-26T09:20:32.526+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Hist_Data_ETL.load_weather_hist_data manual__2024-11-26T09:20:29.197633+00:00 [running]> on host 5de3b6ca18a7
[2024-11-26T09:20:32.610+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Weather_Hist_Data_ETL' AIRFLOW_CTX_TASK_ID='load_weather_hist_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T09:20:29.197633+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T09:20:29.197633+00:00'
[2024-11-26T09:20:32.611+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T09:20:32.616+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-26T09:20:32.616+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-26T09:20:32.617+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-26T09:20:33.208+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T09:20:33.209+0000] {logging_mixin.py:188} INFO - Row count for data to be pushed:  27048
[2024-11-26T09:20:33.343+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T09:20:33.453+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T09:20:33.632+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T09:20:33.633+0000] {logging_mixin.py:188} INFO - File format created successfully.
[2024-11-26T09:20:33.840+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T09:20:33.840+0000] {logging_mixin.py:188} INFO - Stage created successfully.
[2024-11-26T09:20:34.060+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T09:20:34.061+0000] {logging_mixin.py:188} INFO - An error occurred during data load: 'PlainXComArg' object has no attribute 'to_csv'
[2024-11-26T09:20:34.061+0000] {connection.py:762} INFO - closed
[2024-11-26T09:20:34.105+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-26T09:20:34.177+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-26T09:20:34.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T09:20:34.190+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Hist_Data_ETL, task_id=load_weather_hist_data, run_id=manual__2024-11-26T09:20:29.197633+00:00, execution_date=20241126T092029, start_date=20241126T092032, end_date=20241126T092034
[2024-11-26T09:20:34.231+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-26T09:20:34.245+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T09:20:34.247+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
