[2024-11-26T19:20:40.696+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T19:20:40.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:20:37.296736+00:00 [queued]>
[2024-11-26T19:20:40.709+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:20:37.296736+00:00 [queued]>
[2024-11-26T19:20:40.709+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-26T19:20:40.715+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_current_data> on 2024-11-26 19:20:37.296736+00:00
[2024-11-26T19:20:40.720+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=20227) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T19:20:40.720+0000] {standard_task_runner.py:63} INFO - Started process 20230 to run task
[2024-11-26T19:20:40.720+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Realtime_Data_ETL', 'load_weather_current_data', 'manual__2024-11-26T19:20:37.296736+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/ETL_weather_realtime.py', '--cfg-path', '/tmp/tmpblooe46s']
[2024-11-26T19:20:40.721+0000] {standard_task_runner.py:91} INFO - Job 224: Subtask load_weather_current_data
[2024-11-26T19:20:40.749+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:20:37.296736+00:00 [running]> on host 5de3b6ca18a7
[2024-11-26T19:20:40.831+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Weather_Realtime_Data_ETL' AIRFLOW_CTX_TASK_ID='load_weather_current_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T19:20:37.296736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T19:20:37.296736+00:00'
[2024-11-26T19:20:40.832+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T19:20:40.837+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-26T19:20:40.838+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-26T19:20:40.839+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-26T19:20:41.405+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:20:41.412+0000] {logging_mixin.py:188} INFO - Realtime Record to be pushed to snowflake table:                   date  temp  temp_feel  humidity  rain  year  month  day  hour
0 2024-11-26 14:15:00  60.1       60.1        60  2.01  2024     11   26    14
[2024-11-26T19:20:41.527+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:20:41.629+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:20:42.021+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:20:42.022+0000] {logging_mixin.py:188} INFO - Target Table Initialized and Ready to Store Realtime Weather Data from ETL
[2024-11-26T19:20:42.818+0000] {logging_mixin.py:188} INFO - Inserted current weather for date: 2024-11-26 14:15:00
[2024-11-26T19:20:43.065+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:20:43.066+0000] {logging_mixin.py:188} INFO - An error occurred during realtime weather data load: 001003 (42000): 01b8a2a8-0004-3865-0002-55f30003c8fa: SQL compilation error:
syntax error line 2 at position 20 unexpected '%'.
syntax error line 2 at position 24 unexpected '%'.
syntax error line 2 at position 28 unexpected '%'.
syntax error line 2 at position 32 unexpected '%'.
syntax error line 2 at position 36 unexpected '%'.
syntax error line 2 at position 40 unexpected '%'.
syntax error line 2 at position 44 unexpected '%'.
syntax error line 2 at position 48 unexpected '%'.
syntax error line 2 at position 52 unexpected '%'.
[2024-11-26T19:20:43.066+0000] {connection.py:762} INFO - closed
[2024-11-26T19:20:43.107+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-26T19:20:43.160+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-26T19:20:43.161+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T19:20:43.166+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Realtime_Data_ETL, task_id=load_weather_current_data, run_id=manual__2024-11-26T19:20:37.296736+00:00, execution_date=20241126T192037, start_date=20241126T192040, end_date=20241126T192043
[2024-11-26T19:20:43.192+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-26T19:20:43.202+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T19:20:43.203+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
