[2024-11-27T23:08:56.933+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T23:08:56.941+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data scheduled__2024-11-26T21:30:00+00:00 [queued]>
[2024-11-27T23:08:56.946+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data scheduled__2024-11-26T21:30:00+00:00 [queued]>
[2024-11-27T23:08:56.948+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-27T23:08:56.954+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_citibike_data> on 2024-11-26 21:30:00+00:00
[2024-11-27T23:08:56.961+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=40686) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T23:08:56.962+0000] {standard_task_runner.py:63} INFO - Started process 40710 to run task
[2024-11-27T23:08:56.962+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Citibike_Hist_Data_ETL', 'extract_citibike_data', 'scheduled__2024-11-26T21:30:00+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/ETL_citibike.py', '--cfg-path', '/tmp/tmpqqfacnrg']
[2024-11-27T23:08:56.964+0000] {standard_task_runner.py:91} INFO - Job 386: Subtask extract_citibike_data
[2024-11-27T23:08:57.018+0000] {task_command.py:426} INFO - Running <TaskInstance: Citibike_Hist_Data_ETL.extract_citibike_data scheduled__2024-11-26T21:30:00+00:00 [running]> on host 5de3b6ca18a7
[2024-11-27T23:08:57.081+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Citibike_Hist_Data_ETL' AIRFLOW_CTX_TASK_ID='extract_citibike_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T21:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T21:30:00+00:00'
[2024-11-27T23:08:57.082+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T23:08:57.084+0000] {logging_mixin.py:188} INFO - Fetching citibike ride data from 2021-10 to 2024-10
[2024-11-27T23:08:57.103+0000] {logging_mixin.py:188} INFO - Failed to process JC-202110-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202110-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff83aa2060>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.115+0000] {logging_mixin.py:188} INFO - Failed to process JC-202111-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202111-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656381a0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.124+0000] {logging_mixin.py:188} INFO - Failed to process JC-202112-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202112-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff83aa2b70>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.128+0000] {logging_mixin.py:188} INFO - Failed to process JC-202201-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202201-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff655f3500>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.132+0000] {logging_mixin.py:188} INFO - Failed to process JC-202202-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202202-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65638e60>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.136+0000] {logging_mixin.py:188} INFO - Failed to process JC-202203-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202203-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639760>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.139+0000] {logging_mixin.py:188} INFO - Failed to process JC-202204-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202204-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563a0f0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.142+0000] {logging_mixin.py:188} INFO - Failed to process JC-202205-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202205-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563a9c0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.145+0000] {logging_mixin.py:188} INFO - Failed to process JC-202206-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202206-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563b3e0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.150+0000] {logging_mixin.py:188} INFO - Failed to process JC-202207-citbike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202207-citbike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff658587a0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.152+0000] {logging_mixin.py:188} INFO - Failed to process JC-202208-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202208-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639f10>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.155+0000] {logging_mixin.py:188} INFO - Failed to process JC-202209-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202209-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639700>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.158+0000] {logging_mixin.py:188} INFO - Failed to process JC-202210-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202210-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656385c0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.161+0000] {logging_mixin.py:188} INFO - Failed to process JC-202211-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202211-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563b9e0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.164+0000] {logging_mixin.py:188} INFO - Failed to process JC-202212-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202212-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65650290>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.166+0000] {logging_mixin.py:188} INFO - Failed to process JC-202301-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202301-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656380e0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.172+0000] {logging_mixin.py:188} INFO - Failed to process JC-202302-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202302-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639ee0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.175+0000] {logging_mixin.py:188} INFO - Failed to process JC-202303-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202303-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff83aa0890>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.177+0000] {logging_mixin.py:188} INFO - Failed to process JC-202304-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202304-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65650380>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.180+0000] {logging_mixin.py:188} INFO - Failed to process JC-202305-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202305-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65650c20>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.183+0000] {logging_mixin.py:188} INFO - Failed to process JC-202306-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202306-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656514f0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.188+0000] {logging_mixin.py:188} INFO - Failed to process JC-202307-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202307-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656384d0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.192+0000] {logging_mixin.py:188} INFO - Failed to process JC-202308-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202308-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65639be0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.194+0000] {logging_mixin.py:188} INFO - Failed to process JC-202309-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202309-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563b800>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.198+0000] {logging_mixin.py:188} INFO - Failed to process JC-202310-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202310-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65650650>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.201+0000] {logging_mixin.py:188} INFO - Failed to process JC-202311-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202311-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65651c10>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.206+0000] {logging_mixin.py:188} INFO - Failed to process JC-202312-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202312-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656524e0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.211+0000] {logging_mixin.py:188} INFO - Failed to process JC-202401-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202401-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656397c0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.214+0000] {logging_mixin.py:188} INFO - Failed to process JC-202402-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202402-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff83aa14f0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.218+0000] {logging_mixin.py:188} INFO - Failed to process JC-202403-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202403-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65651c10>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.222+0000] {logging_mixin.py:188} INFO - Failed to process JC-202404-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202404-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656505f0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.225+0000] {logging_mixin.py:188} INFO - Failed to process JC-202405-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202405-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65652a20>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.228+0000] {logging_mixin.py:188} INFO - Failed to process JC-202406-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202406-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff65653290>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.231+0000] {logging_mixin.py:188} INFO - Failed to process JC-202407-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202407-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff656387a0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.234+0000] {logging_mixin.py:188} INFO - Failed to process JC-202408-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202408-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563a720>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.236+0000] {logging_mixin.py:188} INFO - Failed to process JC-202409-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202409-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563baa0>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.239+0000] {logging_mixin.py:188} INFO - Failed to process JC-202410-citibike-tripdata.csv.zip during extraction: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /tripdata/JC-202410-citibike-tripdata.csv.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff6563af30>: Failed to resolve 's3.amazonaws.com' ([Errno -2] Name or service not known)"))
[2024-11-27T23:08:57.239+0000] {logging_mixin.py:188} INFO - No data extracted for given range.
[2024-11-27T23:08:57.239+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-27T23:08:57.239+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T23:08:57.243+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Citibike_Hist_Data_ETL, task_id=extract_citibike_data, run_id=scheduled__2024-11-26T21:30:00+00:00, execution_date=20241126T213000, start_date=20241127T230856, end_date=20241127T230857
[2024-11-27T23:08:57.267+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-27T23:08:57.278+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-27T23:08:57.279+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
